"""add model_pricing, audit_logs, enhance request_logs

Revision ID: b322fabf031b
Revises: b5b1d61839d4
Create Date: 2026-05-11 02:17:58.229283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b322fabf031b'
down_revision: Union[str, Sequence[str], None] = 'b5b1d61839d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('input_per_1m', sa.Float(), nullable=False),
    sa.Column('output_per_1m', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_pricing_model_name'), ['model_name'], unique=True)

    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_key_prefix', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('backend_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stream', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cost_usd', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_request_logs_request_id'), ['request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_request_id'))
        batch_op.drop_column('cost_usd')
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('error_message')
        batch_op.drop_column('stream')
        batch_op.drop_column('model_type')
        batch_op.drop_column('backend_model')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('api_key_prefix')
        batch_op.drop_column('user_id')
        batch_op.drop_column('request_id')

    with op.batch_alter_table('model_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_pricing_model_name'))

    op.drop_table('model_pricing')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
