"""add_last_used_at_to_ssh_keys

Revision ID: e42b4362bbf0
Revises: d24fbfa4790c
Create Date: 2026-05-12 00:59:31.177878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42b4362bbf0'
down_revision: Union[str, Sequence[str], None] = 'd24fbfa4790c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_keys', schema=None) as batch_op:
        batch_op.drop_column('last_used_at')

    # ### end Alembic commands ###
